import { AudioOutlined, FileOutlined, PlayCircleOutlined, ReloadOutlined, VideoCameraOutlined } from '@ant-design/icons';
import { Button, Layout, message, Modal, Select, Space, Table, Tag, Tooltip, Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import Hls from 'hls.js';
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import fileManagementService from '@/services/file-management.service';
import type { FileMetadata } from '@/types';

const icon = (type: string) => type === 'VIDEO' ? <VideoCameraOutlined /> : type === 'AUDIO' ? <AudioOutlined /> : <FileOutlined />;
export default function FileManagementPage() {
  const navigate = useNavigate(); const [files, setFiles] = useState<FileMetadata[]>([]); const [loading, setLoading] = useState(false); const [type, setType] = useState<string>(); const [preview, setPreview] = useState<FileMetadata>(); const videoRef = useRef<HTMLVideoElement>(null);
  const load = async () => { setLoading(true); try { const page = await fileManagementService.getFiles({ current: 1, size: 100, fileType: type }); setFiles(page.records ?? []); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [type]);
  useEffect(() => { const video = videoRef.current; if (!video || !preview || preview.fileType !== 'VIDEO') return; const source = preview.transcodeStatus === 'DONE' ? fileManagementService.getStreamUrl(preview.id) : preview.previewUrl || preview.fileUrl; if (!source) return; if (Hls.isSupported() && source.endsWith('.m3u8')) { const hls = new Hls(); hls.loadSource(source); hls.attachMedia(video); return () => hls.destroy(); } video.src = source; }, [preview]);
  const convert = async (file: FileMetadata) => { await fileManagementService.convertFormat(file.id); message.success('Transcoding submitted'); await load(); };
  const columns: ColumnsType<FileMetadata> = [{ title: 'File', dataIndex: 'originalName', render: (name, file) => <Space>{icon(file.fileType)}<Typography.Text ellipsis>{name}</Typography.Text></Space> }, { title: 'Type', dataIndex: 'fileType', width: 110 }, { title: 'Size', dataIndex: 'fileSizeReadable', width: 120, render: (value, file) => value || `${file.fileSize} B` }, { title: 'Media info', width: 180, render: (_, file) => <span>{file.duration ? `${Math.round(file.duration)}s` : '-'} {file.resolution || ''}</span> }, { title: 'Status', dataIndex: 'transcodeStatus', width: 120, render: (status) => status ? <Tag color={status === 'DONE' ? 'green' : status === 'FAILED' ? 'red' : 'gold'}>{status}</Tag> : '-' }, { title: 'Actions', width: 150, render: (_, file) => <Space><Tooltip title="Preview"><Button type="text" icon={<PlayCircleOutlined />} disabled={!['VIDEO', 'AUDIO'].includes(file.fileType)} onClick={() => setPreview(file)} /></Tooltip><Tooltip title="Transcode to HLS"><Button type="text" disabled={!['VIDEO', 'AUDIO'].includes(file.fileType)} icon={<ReloadOutlined />} onClick={() => void convert(file)} /></Tooltip></Space> }];
  return <Layout className="workspace-layout"><header className="workspace-header"><Typography.Title level={4}>Knowledge Base</Typography.Title><Button onClick={() => navigate('/')}>Back to dashboard</Button></header><main className="workspace-main"><div className="page-title-row"><div><Typography.Title level={3}>Files</Typography.Title><Typography.Text type="secondary">Manage media and file transcoding status.</Typography.Text></div><Button icon={<ReloadOutlined />} onClick={() => void load()} /></div><Select allowClear placeholder="All file types" value={type} onChange={setType} options={[{ value: 'VIDEO', label: 'Video' }, { value: 'AUDIO', label: 'Audio' }, { value: 'IMAGE', label: 'Image' }, { value: 'DOCUMENT', label: 'Document' }]} /><Table className="documents-table" style={{ marginTop: 16 }} rowKey="id" loading={loading} columns={columns} dataSource={files} pagination={false} /></main><Modal open={Boolean(preview)} footer={null} title={preview?.originalName} onCancel={() => setPreview(undefined)}>{preview?.fileType === 'AUDIO' ? <audio className="media-player" controls src={preview.previewUrl || preview.fileUrl} /> : <video className="media-player" ref={videoRef} controls />}</Modal></Layout>;
}
