import { HistoryOutlined, RobotOutlined, SearchOutlined } from '@ant-design/icons';
import { Button, Card, Empty, Input, Layout, List, Radio, Space, Spin, Tag, Typography } from 'antd';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import searchService from '@/services/search.service';
import type { SearchHistory, SearchResult } from '@/types';

export default function SearchPage() {
  const navigate = useNavigate(); const [keyword, setKeyword] = useState(''); const [mode, setMode] = useState<'keyword' | 'hybrid'>('keyword'); const [results, setResults] = useState<SearchResult[]>([]); const [history, setHistory] = useState<SearchHistory[]>([]); const [loading, setLoading] = useState(false);
  const loadHistory = async () => { try { setHistory(await searchService.history()); } catch { setHistory([]); } };
  useEffect(() => { void loadHistory(); }, []);
  const search = async (value = keyword) => { if (!value.trim()) return; setLoading(true); try { const page = await searchService.search({ keyword: value.trim(), searchMode: mode, size: 20, topK: 20, enableRerank: mode === 'hybrid' }); setResults(page.records ?? []); await loadHistory(); } finally { setLoading(false); } };
  return <Layout className="workspace-layout"><header className="workspace-header"><Typography.Title level={4}>Knowledge Base</Typography.Title><Button onClick={() => navigate('/')}>Back to dashboard</Button></header><main className="workspace-main search-page"><div className="page-title-row"><div><Typography.Title level={3}>Search</Typography.Title><Typography.Text type="secondary">Search published knowledge by keyword or RAG-assisted hybrid retrieval.</Typography.Text></div></div><section className="search-box"><Input size="large" value={keyword} onChange={(event) => setKeyword(event.target.value)} onPressEnter={() => void search()} prefix={<SearchOutlined />} placeholder="Search knowledge" /><Button size="large" type="primary" icon={<SearchOutlined />} onClick={() => void search()}>Search</Button></section><Radio.Group value={mode} onChange={(event) => setMode(event.target.value)}><Radio.Button value="keyword">Keyword</Radio.Button><Radio.Button value="hybrid"><RobotOutlined /> Hybrid</Radio.Button></Radio.Group><div className="search-layout"><section><Spin spinning={loading}>{!loading && results.length === 0 ? <Empty description="Enter a keyword to start searching" /> : <List dataSource={results} renderItem={(item) => <List.Item><Card className="search-result-card" title={<Button type="link" onClick={() => navigate(`/documents/${item.id}`)}>{item.title}</Button>}><Typography.Paragraph ellipsis={{ rows: 3 }}>{item.summary}</Typography.Paragraph><Space wrap>{item.categoryName && <Tag>{item.categoryName}</Tag>}{item.creatorName && <Tag>{item.creatorName}</Tag>}{item.score !== undefined && <Tag color="blue">{item.score.toFixed(2)}</Tag>}</Space></Card></List.Item>} />}</Spin></section><aside className="search-history"><Typography.Text strong><HistoryOutlined /> Recent searches</Typography.Text><List size="small" dataSource={history} locale={{ emptyText: 'No search history' }} renderItem={(item) => <List.Item><Button type="link" onClick={() => { setKeyword(item.keyword); void search(item.keyword); }}>{item.keyword}</Button></List.Item>} /></aside></div></main></Layout>;
}
