import { DeleteOutlined, PlusOutlined, TeamOutlined, UserAddOutlined } from '@ant-design/icons';
import { Button, Form, Input, InputNumber, Layout, List, message, Modal, Popconfirm, Table, Tag, Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import teamService from '@/services/team.service';
import type { Team, TeamMember } from '@/types';

export default function TeamsPage() {
  const navigate = useNavigate(); const [teams, setTeams] = useState<Team[]>([]); const [members, setMembers] = useState<TeamMember[]>([]); const [selected, setSelected] = useState<Team>(); const [loading, setLoading] = useState(false); const [modal, setModal] = useState(false); const [memberModal, setMemberModal] = useState(false); const [form] = Form.useForm(); const [memberForm] = Form.useForm();
  const load = async () => { setLoading(true); try { const page = await teamService.getTeams({ current: 1, size: 100 }); setTeams(page.records ?? []); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const selectTeam = async (team: Team) => { setSelected(team); setMembers(await teamService.getTeamMembers(team.id)); };
  const save = async () => { const value = await form.validateFields(); await teamService.createTeam(value); message.success('Team created'); setModal(false); form.resetFields(); await load(); };
  const addMember = async () => { if (!selected) return; const { userId } = await memberForm.validateFields(); await teamService.addMembers(selected.id, [userId]); message.success('Member added'); setMemberModal(false); memberForm.resetFields(); await selectTeam(selected); await load(); };
  const columns: ColumnsType<Team> = [{ title: 'Team', dataIndex: 'teamName', render: (name, team) => <Button type="link" onClick={() => void selectTeam(team)}>{name}</Button> }, { title: 'Code', dataIndex: 'teamCode' }, { title: 'Leader', dataIndex: 'leaderName', render: (name, team) => name || team.leaderId || '-' }, { title: 'Members', dataIndex: 'memberCount' }, { title: 'Documents', dataIndex: 'docCount' }, { title: 'Status', dataIndex: 'status', render: (status) => <Tag color={status === 1 ? 'green' : 'red'}>{status === 1 ? 'Enabled' : 'Disabled'}</Tag> }, { title: 'Actions', render: (_, team) => <Popconfirm title="Delete this team?" onConfirm={async () => { await teamService.deleteTeam(team.id); if (selected?.id === team.id) { setSelected(undefined); setMembers([]); } await load(); }}><Button danger type="text" icon={<DeleteOutlined />} /></Popconfirm> }];
  return <Layout className="workspace-layout"><header className="workspace-header"><Typography.Title level={4}>Knowledge Base</Typography.Title><Button onClick={() => navigate('/')}>Back to dashboard</Button></header><main className="workspace-main"><div className="page-title-row"><div><Typography.Title level={3}><TeamOutlined /> Teams</Typography.Title><Typography.Text type="secondary">Manage team spaces and members.</Typography.Text></div><Button type="primary" icon={<PlusOutlined />} onClick={() => setModal(true)}>New team</Button></div><section className="management-grid"><Table className="documents-table" rowKey="id" loading={loading} columns={columns} dataSource={teams} pagination={false} /><aside className="team-members"><Typography.Title level={5}>{selected ? `${selected.teamName} members` : 'Select a team'}</Typography.Title>{selected && <Button icon={<UserAddOutlined />} onClick={() => setMemberModal(true)}>Add member</Button>}<List size="small" dataSource={members} locale={{ emptyText: 'No members' }} renderItem={(member) => <List.Item>{member.realName || member.username}<Tag>{member.role}</Tag></List.Item>} /></aside></section></main><Modal title="New team" open={modal} onOk={() => void save()} onCancel={() => setModal(false)}><Form form={form} layout="vertical"><Form.Item name="teamName" label="Team name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="teamCode" label="Team code" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="leaderId" label="Leader ID" rules={[{ required: true }]}><InputNumber style={{ width: '100%' }} /></Form.Item><Form.Item name="description" label="Description"><Input.TextArea /></Form.Item></Form></Modal><Modal title="Add member" open={memberModal} onOk={() => void addMember()} onCancel={() => setMemberModal(false)}><Form form={memberForm} layout="vertical"><Form.Item name="userId" label="User ID" rules={[{ required: true }]}><InputNumber style={{ width: '100%' }} /></Form.Item></Form></Modal></Layout>;
}
