import { DeleteOutlined, EditOutlined, MailOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { Button, Form, Input, Layout, Modal, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { userService, type UserForm, type InviteUserForm } from '@/services/user.service';
import teamService from '@/services/team.service';
import type { Team } from '@/types';
import type { User } from '@/types';

export default function UsersPage() {
  const navigate = useNavigate(); const [users, setUsers] = useState<User[]>([]); const [teams, setTeams] = useState<Team[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false); const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState<number>(); const [page, setPage] = useState(1); const [modalOpen, setModalOpen] = useState(false); const [inviteOpen, setInviteOpen] = useState(false); const [editing, setEditing] = useState<User>(); const [form] = Form.useForm<UserForm>(); const [inviteForm] = Form.useForm<InviteUserForm>();
  const load = async (current = page) => { setLoading(true); try { const result = await userService.page({ current, size: 10, keyword: keyword || undefined, status }); setUsers(result.records); setTotal(result.total); } finally { setLoading(false); } };
  useEffect(() => { void load(); void teamService.getTeamTree().then(setTeams); }, [page, status]);
  const openForm = (user?: User) => { setEditing(user); form.resetFields(); if (user) form.setFieldsValue({ ...user, phone: user.phone ?? undefined }); else form.setFieldsValue({ status: 1 }); setModalOpen(true); };
  const save = async () => { const values = await form.validateFields(); if (editing?.id) await userService.update({ ...values, id: editing.id }); else await userService.create(values); setModalOpen(false); await load(); message.success('User saved'); };
  const remove = async (id: number) => { await userService.remove(id); await load(); message.success('User deleted'); };
  const sendInvite = async () => { const values = await inviteForm.validateFields(); await userService.invite(values); setInviteOpen(false); inviteForm.resetFields(); await load(); message.success('Invitation sent'); };
  const columns: ColumnsType<User> = [{ title: 'Username', dataIndex: 'username' }, { title: 'Email', dataIndex: 'email', render: (v) => v || '-' }, { title: 'Real name', dataIndex: 'realName', render: (v) => v || '-' }, { title: 'Department', dataIndex: 'department', render: (v) => v || '-' }, { title: 'Status', dataIndex: 'status', render: (v) => <Tag color={v === 1 ? 'green' : 'red'}>{v === 1 ? 'Enabled' : 'Disabled'}</Tag> }, { title: 'Actions', render: (_, user) => <Space><Button type="text" icon={<EditOutlined />} onClick={() => openForm(user)} /><Popconfirm title="Delete this user?" onConfirm={() => user.id && void remove(user.id)}><Button type="text" danger icon={<DeleteOutlined />} /></Popconfirm></Space> }];
  return <Layout className="workspace-layout"><header className="workspace-header"><Typography.Title level={4}>Knowledge Base</Typography.Title><Button onClick={() => navigate('/')}>Back to dashboard</Button></header><main className="workspace-main"><div className="page-title-row"><div><Typography.Title level={3}>Users</Typography.Title><Typography.Text type="secondary">Invite and manage team members</Typography.Text></div><Space><Button type="primary" icon={<MailOutlined />} onClick={() => { inviteForm.resetFields(); setInviteOpen(true); }}>Invite member</Button></Space></div><section className="table-toolbar"><Input value={keyword} onChange={(e) => setKeyword(e.target.value)} onPressEnter={() => { setPage(1); void load(1); }} prefix={<SearchOutlined />} placeholder="Search users" /><Select allowClear value={status} onChange={(value) => { setStatus(value); setPage(1); }} placeholder="Status" options={[{ value: 1, label: 'Enabled' }, { value: 0, label: 'Pending/disabled' }]} /><Button icon={<SearchOutlined />} onClick={() => { setPage(1); void load(1); }}>Search</Button><Button icon={<ReloadOutlined />} onClick={() => { setKeyword(''); setStatus(undefined); setPage(1); }} /></section><Table className="documents-table" rowKey="id" loading={loading} columns={columns} dataSource={users} pagination={{ current: page, pageSize: 10, total, onChange: setPage }} /></main><Modal title={editing ? 'Edit user' : 'New user'} open={modalOpen} onOk={() => void save()} onCancel={() => setModalOpen(false)}><Form form={form} layout="vertical"><Form.Item label="Username" name="username" rules={[{ required: true }]}><Input disabled={Boolean(editing)} /></Form.Item>{!editing && <Form.Item label="Password" name="password" rules={[{ required: true, min: 6 }]}><Input.Password /></Form.Item>}<Form.Item label="Email" name="email"><Input /></Form.Item><Form.Item label="Real name" name="realName"><Input /></Form.Item><Form.Item label="Department" name="department"><Input /></Form.Item><Form.Item label="Position" name="position"><Input /></Form.Item><Form.Item label="Status" name="status"><Select options={[{ value: 1, label: 'Enabled' }, { value: 0, label: 'Disabled' }]} /></Form.Item></Form></Modal><Modal title="Invite team member" open={inviteOpen} onOk={() => void sendInvite()} onCancel={() => setInviteOpen(false)}><Form form={inviteForm} layout="vertical"><Form.Item label="Username" name="username" rules={[{ required: true, min: 4, max: 20 }]}><Input /></Form.Item><Form.Item label="Email" name="email" rules={[{ required: true, type: 'email' }]}><Input /></Form.Item><Form.Item label="Real name" name="realName" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="Phone" name="phone"><Input /></Form.Item><Form.Item label="Team" name="teamId" rules={[{ required: true }]}><Select options={teams.map((team) => ({ value: team.id, label: team.teamName }))} /></Form.Item></Form></Modal></Layout>;
}
